variables:
  CONTAINER_PROJECT_PATH: /uc1-recruit/notify

include:
  - project: "devops/ci-templates"
    file: "/standard/.container-build.yml"

e2e:
  extends:
    - .job_defaults
    - .registry_login
  stage: test
  image:
    name: docker/compose:1.29.0
    entrypoint: [""]
  before_script:
    - export IMAGE_TAG=$CI_COMMIT_SHORT_SHA
  script:
    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID-e2e -f tests/e2e/docker-compose.yml up --abort-on-container-exit
  after_script:
    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID-e2e -f tests/e2e/docker-compose.yml logs
    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID-e2e -f tests/e2e/docker-compose.yml down --volumes --remove-orphans
