variables:
  CONTAINER_REGISTRY_HOST: ghcr.io
  CONTAINER_PROJECT_PATH: /miracum/recruit/notify

include:
  - project: "devops/ci-templates"
    file: "/standard/.container-build.yml"

.registry_login:
  before_script:
    - echo $GHCR_REGISTRY_PASSWORD | docker login -u $GHCR_REGISTRY_USERNAME $CONTAINER_REGISTRY_HOST --password-stdin
  after_script:
    - docker logout $CONTAINER_REGISTRY_HOST

build:
  coverage: '/\d+.\d+ \% covered/'

e2e:
  extends:
    - .job_defaults
    - .registry_login
  stage: test
  image:
    name: docker/compose:1.29.2
    entrypoint: [""]
  before_script:
    - export IMAGE_TAG=$CI_COMMIT_SHORT_SHA
  script:
    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID-e2e -f tests/e2e/docker-compose.yml up --abort-on-container-exit
  after_script:
    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID-e2e -f tests/e2e/docker-compose.yml logs
    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID-e2e -f tests/e2e/docker-compose.yml down --volumes --remove-orphans
