fhir:
  url: ""
  subscription:
    criteria: "List?code=https://fhir.miracum.org/uc1/CodeSystem/screeningList|screening-recommendations"
  systems:
    screeninglistReference: "https://fhir.miracum.org/uc1/StructureDefinition/belongsToStudy"
    studyAcronym: "https://fhir.miracum.org/uc1/StructureDefinition/studyAcronym"

webhook:
  endpoint: "http://localhost:8080/on-list-change"

spring:
  mail: {}
  profiles:
    active: dev

management:
  endpoint:
    health:
      show-details: always
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

notify:
  screeningListLinkTemplate: ""
  rules:
    mail: []
  version: 0.0.0-dev
  retry:
    backoffPeriodMs: 10000
    maxAttempts: 10
