fhir:
  url: ""
  subscription:
    criteria: "List?code=https://fhir.miracum.org/uc1/CodeSystem/screeningList|screening-recommendations"
  systems:
    screeninglistReference: "https://fhir.miracum.org/uc1/StructureDefinition/belongsToStudy"
    studyAcronym: "https://fhir.miracum.org/uc1/StructureDefinition/studyAcronym"

webhook:
  endpoint: ""

retry:
  backoffPeriod: 10000
  maxAttempts: 10

spring:
  mail: {}
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "health, prometheus, info"
      base-path: /
      path-mapping:
        health: health
        prometheus: metrics

notify:
  screeningListLinkTemplate: ""
  rules:
    mail: []
