notify:
  version: 0.0.0-dev
  retry:
    backoffPeriodMs: 10000
    maxAttempts: 10
  mailer:
    from: "rekrutierungsvorschlag@miracum.org"
    link-template: "http://replace-host-name:8083/recommendations/[list_id]"
    subject: "MIRACUM Rekrutierungsunterstützung: neue Vorschläge für die Studie [study_acronym]"
  rules: {}

spring:
  application:
    name: "notify"
  mail:
    host:
    port: 25
    username:
    password:
    properties:
      mail:
        debug: true
  profiles:
    active: dev

webhook:
  endpoint: "http://host.docker.internal:8080/on-list-change"

fhir:
  url: ""
  subscription:
    criteria: "List?code=https://fhir.miracum.org/uc1/CodeSystem/screeningList|screening-recommendations"
  systems:
    screeninglistReference: "https://fhir.miracum.org/uc1/StructureDefinition/belongsToStudy"
    studyAcronym: "https://fhir.miracum.org/uc1/StructureDefinition/studyAcronym"
    subscriberSystem: "https://fhir.miracum.org/uc1/NamingSystem/notificationSubscriberId"
    communication: "https://fhir.miracum.org/uc1/NamingSystem/notificationId"
  communication:
    payloadText: "Notify: Temporary Stored Message"
    systemValue: "MIRACUM Notify"

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

opentracing:
  jaeger:
    log-spans: false
    include-jaeger-env-tags: true
    enabled: false
