services:
  fhir:
    image: docker.io/hapiproject/hapi:v5.6.0-distroless
    environment:
      HAPI_FHIR_VALIDATION_REQUESTS_ENABLED: "true"
      HAPI_FHIR_SUBSCRIPTION_RESTHOOK_ENABLED: "true"
      HAPI_FHIR_FHIR_VERSION: "R4"
      HAPI_FHIR_CORS_ALLOWCREDENTIALS: "false"
      HAPI_FHIR_CORS_ALLOWED_ORIGIN: "*"
    ports:
      - "8082:8080"

  jobstore-db:
    image: docker.io/postgres:14.1
    environment:
      POSTGRES_PASSWORD: postgres # pragma: allowlist secret
      POSTGRES_DB: recruit_notify_jobs
    ports:
      - "6432:5432"

  list:
    image: ghcr.io/miracum/recruit/list:v2.14.2
    ports:
      - "8083:8080"
    environment:
      FHIR_URL: "http://fhir:8080/fhir"
      KEYCLOAK_DISABLED: "true"

  maildev:
    image: docker.io/djfarrelly/maildev:1.1.0
    ports:
      - "3025:25"
      - "2080:80"

  loader:
    image: docker.io/curlimages/curl:7.80.0
    command: >
      -X POST
      -H "Content-Type: application/json"
      --retry-connrefuse
      --connect-timeout 10
      --max-time 60
      --retry 5
      --retry-delay 10
      --data "@/data/screening-list-sample.json"
      http://fhir:8080/fhir
    depends_on:
      - fhir
    volumes:
      - ./data:/data:ro

  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.28
    ports:
      - 16686:16686
      - 6831:6831/udp
