version: "3.7"

services:
  fhir:
    image: docker.miracum.org/miracum-data/hapi-fhir-jpaserver:v6.1.0
    ports:
      - "8082:8080"
    environment:
      server.address: "http://localhost:8082/fhir"
      subscription.resthook.enabled: "true"
      subscription.websocket.enabled: "false"

  list:
    image: docker.miracum.org/uc1-recruit/list:v1.12.6
    restart: always
    ports:
      - "8083:3000"
    environment:
      FHIR_URL: "http://fhir:8080/fhir"

  greenmail:
    image: greenmail/standalone:1.5.11
    ports:
      - "3025:3025"
    environment:
      GREENMAIL_OPTS: "-Dgreenmail.setup.test.all -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.auth.disabled -Dgreenmail.verbose"

  loader:
    image: byrnedo/alpine-curl:0.1.8
    command: -X POST
      -H "Content-Type:application/json"
      --retry-connrefuse
      --connect-timeout 10
      --max-time 60
      --retry 5
      --retry-delay 10
      --data "@/data/screening-list-sample.json"
      http://fhir:8080/fhir
    depends_on:
      - fhir
    volumes:
      - ./data:/data
