version: "3.7"

services:
  fhir:
    image: docker.miracum.org/miracum-data/hapi-fhir-jpaserver:v8.1.3
    ports:
      - "8082:8080"
    environment:
      subscription.resthook.enabled: "true"
      subscription.websocket.enabled: "false"

  list:
    image: docker.miracum.org/uc1-recruit/list:2.4
    restart: always
    ports:
      - "8083:8080"
    environment:
      FHIR_URL: "http://fhir:8080/fhir"
      KEYCLOAK_DISABLED: "true"

  maildev:
    image: djfarrelly/maildev:1.1.0
    ports:
      - "3025:25"
      - "2080:80"

  loader:
    image: curlimages/curl:7.75.0
    command: >
      -X POST
      -H "Content-Type: application/json"
      --retry-connrefuse
      --connect-timeout 10
      --max-time 60
      --retry 5
      --retry-delay 10
      --data "@/data/screening-list-sample.json"
      http://fhir:8080/fhir
    depends_on:
      - fhir
    volumes:
      - ./data:/data:ro
